version: '3.9'

services:
  integration_tests:
    container_name: integration_tests
    build:
      context: ../
      dockerfile: ./build/integrationtests/Dockerfile
    env_file:
    - ../configs/config.env
    restart: always
    depends_on:
       cbrwsdltojson:
        condition: service_started
    volumes:
    - type: bind
      source: .
      target: /deployLogs
    networks:
    - default_network
