version: '3.9'

services:
  cbrwsdltojson:
    container_name: cbrwsdltojson
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    env_file:
    - ../configs/config.env
    restart: always
    ports:
      - "4000:4000"
    networks:
    - default_network
networks:
  default_network:
    driver: host
  